### ISSUE TITLE
Support for redis via ioredis

### ISSUE THREAD

**Issue by killerdroid99** [jcs224/hono_sessions#8]
Can the session store be implemented with redis using ioredis?

**Comment by jcs224** [comment]
A driver can be made for `ioredis`, but I'm wondering if this would be better as an external driver than part of the `hono-sessions` library. For the core package, I only want to support databases included with the core of the runtime, such as Bun SQLite or Deno KV. I may put guidance in the readme for how to create your own storage driver. This is similar in approach to Golang's Gorilla Sessions.

I found this Redis driver for `hono-sessions`, it's `node-redis` instead of `ioredis` though.

https://github.com/crossunit/connect-redis-hono

**Comment by jcs224** [comment]
Here's an ioredis port

https://www.npmjs.com/package/hono-sessions-redis
